### PR TITLE
77 bytes for the most basic version

### PR DESCRIPTION
**Pull request by p01**
Sorry I missed the discussion about this project, but did you folks see a problem with this approach ?

### CODE REVIEW

**Comment by xem** [comment]
thanks! I'll use the 73b version though

**Comment by p01** [comment]
Too bad,  PR are cheap.
Golfing on git and github shows the evolution of a piece of code.

**Comment by xem** [comment]
Sorry, but don't worry, I'm writing a detailes article about this piece of golf :)

**Comment by xem** [comment]
nevermind, accepting your PR and pasting the new version over :p

**Pull request merged**
